AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  SuggestExtensions: false
  Exclude:
    - "gemfiles/**/*"
    - "vendor/**/*"

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"

Gemspec/DevelopmentDependencies:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Exclude:
    - "spec/integration/end_to_end_spec.rb"
